---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 27220.
--- DateTime: 2024/1/21 12:28
---

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
-- 库存key(存放库存) string类型
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key(存放下单用户id) set 集合
local orderKey = 'seckill:order:' .. voucherId

--库存不足
if (tonumber(redis.call('get',stockKey)) <= 0) then
    --库存不足
    return 1
end
if (redis.call('sismember',orderKey,userId) == 1) then
    --存在，说明重复下单
    return 2
end
--正常下单
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
--向队列中放数据
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0
