---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 27220.
--- DateTime: 2024/1/20 11:47
---
---判断锁是否是自己的，是的话释放
if (redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0